### ISSUE TITLE
Need to loop though portfolio's id's, to get data

### ISSUE THREAD

**Issue by SubaruSteve** [jontymorris/Sharesies-API#12]
I still can't come up with a way to directly access an 'instruments' data, with it's id, I've tried multiple approaches.

NOTE: This API client is not supported by Sharesies.co.nz, you should talk to Sharesies and be sure you are complying with reasonable use and not breaching any terms of service or law before accessing their system with any of the code in this and any similar repository.

**Comment by jontymorris** [comment]
@SubaruSteve another great suggestion - I have now added a `sharesies.client.get_instrument` method.

e.g
```python
import sharesies
client = sharesies.Client()
client.login('example', 'password')

# get TSLA by ID
client.get_instrument('f7b92c2a-7240-407f-a6f4-55bc8d26bdc0')
```
More information can be obtained through methods such as `get_dividends`, `get_price_history`, and `get_order_history`.

Would love to see you chuck up a PR with your suggestions in the future :)

Let me know if this isn't what you were after, cheers

See commit 
https://github.com/jontymorris/Sharesies-API/commit/83d9fc3d794ede7a3f3039d68c41e97116ce3d17

**Comment by SubaruSteve** [comment]
All I'm getting out of this is my profile sent back to me.

**Comment by jontymorris** [comment]
@SubaruSteve damn looks like a misleading endpoint. Was one the wines last night so barely checked the data.

Give it another go now
