### ISSUE TITLE
Need to logout?

### ISSUE THREAD

**Issue by SubaruSteve** [jontymorris/Sharesies-API#13]
Do we need a logout function?

NOTE: This API client is not supported by Sharesies.co.nz, you should talk to Sharesies and be sure you are complying with reasonable use and not breaching any terms of service or law before accessing their system with any of the code in this and any similar repository.

**Comment by jontymorris** [comment]
@SubaruSteve I like this idea, the only previous way to do this was create a new `sharesies.Client`.

Have now added a new sharesies.Client.logout method

e.g.
```python
import sharesies
client = sharesies.Client()
client.login('example', 'password')
client.logout()
```

See commit
https://github.com/jontymorris/Sharesies-API/commit/83d9fc3d794ede7a3f3039d68c41e97116ce3d17
