### ISSUE TITLE
Buy/sell history

### ISSUE THREAD

**Issue by mhjb** [jontymorris/Sharesies-API#8]
Love your work thank you @jontymorris.

Do you know if there's a way of seeing one's buy/sell history for a particular stock (or all stocks)? I want to show the percentage change between the current price and my last buy/sell.

**Comment by jontymorris** [comment]
Thanks for taking an interest @mhjb :)

I think that'd be a really cool/helpful feature so I have added support for order history. Update your Sharesies-API and try the example below.

Let me know if you have questions/issues :+1: 

```python
# get your portfolio
profile = client.get_profile()
portfolio = profile['portfolio']

# loop through your portfolio
for item in portfolio:
  fund_id = item['fund_id']
  order_history = client.get_order_history(fund_id)
  
  '''
  each item has:
    type: buy/sell
    contribution: amount buy/sold
    order_unit_price: price at time
    created: Unix timestamp
  '''
```

**Comment by mhjb** [comment]
Fast work!
That did the trick; thank you very much
